site_name: EPITECH Documentation
repo_url: https://github.com/epitools2024/epitech-documentation.git
site_description: "All you will use at EPITECH"
site_author: epitools2024

theme:
    name: readthedocs
    colorscheme: github
    shortcuts:
        next: 78
        previous: 80
        search: 83

nav:
    - HOME: index.md
    - ABOUT EPITECH:
        - Epitech PEDAGOGY: about_epitech/epitech.md
        - Links & Documents: about_epitech/links_docs.md
    - INSTALLATION & CONFIGURATIONS:
        - Windows + Linux Distro: install_config/dual_boot.md
        - EPITECH DUMP: install_config/dump.md
    - TOOLS CHEATSHEET:
        - Blih: tools_cheatsheet/blih.md
        - Git: tools_cheatsheet/git.md
        - Emacs: tools_cheatsheet/emacs.md
        - Gcc: tools_cheatsheet/gcc.md
        - Makefile: tools_cheatsheet/Makefile.md
        - Coding Style: tools_cheatsheet/coding_style.md
        - TTY: tools_cheatsheet/TTY.md
       
    - C PROGRAMMING:
        - Simples functions: c_programming/functions.md
        - libraries :
            - Csfml Library: tools_cheatsheet/csfml.md
            - Ncurses Library: tools_cheatsheet/ncurses.md
            - Your Library: c_programming/libmy.md
        - Notions :
            - Structures: c_programming/structures.md
            - Lists: c_programming/lists.md
            - Pointers: c_programming/pointers.md
            - Unit Test: c_programming/unit_test.md
            - Typedef Keyword: c_programming/typedef_keyword.md
            - Preprocessor: 
                - Intro: c_programming/preprocessor.md
                - Include Guards: c_programming/include_guards.md
                - Macros: c_programming/macros.md

    - ABOUT US:
        - EPITOOLS: about_us/epitools.md
        - Contribution: about_us/contribution.md
        - LICENSE: about_us/license.md

markdown_extensions:
    - toc:
        baselevel: 2

copyright: EPITOOLS 2024